# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
palette = 'catppuccin_mocha'

# format = '''
# [┌─────────────────[$shell]()──>](bold green)
# [│](bold green)$username$directory
# [└─$character](bold green) '''

# format = '> $all >'

format = '$shell$username$hostname$directory$git_branch$character'

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[✗](bold red)'
format = ' $symbol '

[directory]
truncation_length = 1
# truncation_symbol = '…/'
home_symbol = '🏠'
# format = '\([$path]($style)\)[$read_only]($read_only_style) '
format = '[\($path\)]($style)[$read_only]($read_only_style)'
style = 'inverted bold lavender'

[aws]
disabled = true

[line_break]
disabled = true

[hostname]
# ssh_symbol = ' 🛜'
# format = '@[$hostname$ssh_symbol]($style)'
format = '[@$hostname]($style)'
ssh_only = false
style = 'inverted pink'

[username]
format = '[$user]($style)'
show_always = true
# aliases = { "aj" = "matchai" }
style_user = 'inverted rosewater'

[git_branch]
format = '[\($branch(:$remote_branch)\)]($style)'
# format = '[$symbol\($branch(:$remote_branch)\)]($style) '
# symbol = '🌱'
style = 'inverted rosewater'

[git_status]
disabled = true

[localip]
format = '[\($localipv4\)]($style) '
disabled = true

[os]
disabled = true

[python]
disabled = true

[terraform]
disabled = false
# format = '[\[tf $version\]]($style) '

[shell]
disabled = false
# zsh_indicator = ''
# bash_indicator = ''
# powershell_indicator = '⌗'
format = '[$indicator>]($style)'
style = 'inverted dimmed lavender'

[package]
disabled = true

[status]
disabled = true

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
