# set -g mode-keys vi
set -g status-position bottom

set -g default-terminal 'screen-256color'
set -g history-file ~/._tmux-history

# tmux adds a short, almost imperceptible delay between the commands that can cause funny behavior when running vim inside tmux.
set -s escape-time 0
set -g mouse on

#############################
# Leader Key
#############################
unbind `
unbind §
set -g prefix `
set -g prefix2 §
bind ` send-prefix
bind § send-prefix -2

#############################
# numbering and naming
#############################
set -g base-index 1
set -g renumber-windows on
set-window-option -g pane-base-index 1
set -g allow-rename on

# Increase scrollback buffer size from 2000 to 50000 lines
set-option -g history-limit 50000
# Focus events enabled for terminals that support them
set -g focus-events on

#############################
# key binding
#############################
bind r {
  source-file ~/.tmux.conf
  display 'config reloaded'
}

bind e split-window -hc "#{pane_current_path}" ranger

#############################
# navigation
#############################
bind | split-window -hc "#{pane_current_path}"
bind \\ split-window -hc "#{pane_current_path}"
bind - split-window -vc "#{pane_current_path}"

bind-key Up select-pane -U
bind-key Down select-pane -D
bind-key Left select-pane -L
bind-key Right select-pane -R
# switch panes using Alt-arrow without prefix
unbind -n M-Left
unbind -n M-Right
unbind -n M-Up
unbind -n M-Down
#bind -n M-Left select-pane -L
#bind -n M-Right select-pane -R
#bind -n M-Up select-pane -U
#bind -n M-Down select-pane -D

bind n new-window -c "#{pane_current_path}"

bind Space last-window
bind-key -n M-Tab last-window

#############################
#############################
# display
#############################
#############################
set -g display-time 2000

# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# Pane divider
set-window-option -g pane-border-style fg=red
set-window-option -g pane-active-border-style fg=yellow

# Cool trick: Let's dim out any pane that's not active.
set-window-option -g window-style fg=white,bg=colour236
set-window-option -g window-active-style fg=white,bg=colour235

# Command / Message line
set-window-option -g message-style fg=black,bold,bg=colour11

#############################
# Status Bar
#############################
set-option -g status on
set-option -g status-style fg=white,bg=colour04
set-option -g status-justify centre
set-window-option -g window-status-style fg=red,bg=black
set-window-option -g window-status-current-style fg=black,bold,bg=white
# set-window-option -g window-status-last-style fg=black,bold,bg=colour011
# set-window-option -g window-status-separator |

# Left Side
# Show my active session, window, pane name or id
set-option -g status-left-length 50   # default 10
set-option -g status-left "[#[fg=white]S: #S, #[fg=colour11]W #I-#W, #[fg=colour3]P: #P #[fg=white]]"
# set-option -g status-left-style

# Right Side
set-option -g status-right-length 50   # default 50
set-option -g status-right "#[fg=blue,italics,bg=white] ⬟ #(kubectl config current-context)"

# Enable Activity Alerts
set-option -g status-interval 15           # Update the status line every 60 seconds (15 is default)
set-window-option -g monitor-activity on   # highlights the window name in the status line
